language: java
cache:
  directories:
  - $HOME/.gradle

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build jacocoTestReport

notifications:
  email:
    recipients:
      - panashchenko89@gmail.com